site:
  title: OpenCPN Manuals
  url: https://rasbats.github.io/ocpn-manuals/
  start_page:  manuals::index.adoc

content:
  sources:
    - url: https://github.com/Rasbats/ocpn-manuals
      branches: manual
      edit_url: true
      start_paths:
      - manuals
      - dev
      - plugins/manual
      - plugins/manual-beta
    
    - url: .
      branches: HEAD
      start_path: ./sources/

    - url: .
      branches: HEAD
      start_path: ./sources/admiralty_tide_tables_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/aisradar_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/autopilot_route_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/Autopilot-Plugin
    
    - url: .
      branches: HEAD
      start_path: ./sources/bsb4_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/calculator_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/celestial_navigation_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/chartscale_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/climatology_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/dashboard_tactics_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/DR_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/EarthExplorer_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/FindIt_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/gecomapi_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/GPS-Odometer_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/iacfleet_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/launcher_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/LogbookKonni_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/NmeaConverter_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/nvc_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/objsearch_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/ocpn_draw_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/ocpndebugger_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/oeSENC_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/ofc_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/otcurrent_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/otidalplan_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/otidalroute_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/photolayer_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/plots_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/polar_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/projections_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/pypilot_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/radar_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/rotationctrl_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/route_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/rtlsdr_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/s63_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/SailawayNMEA_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/sar_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/shipdriver_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/statusbar_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/survey_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/tactics_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/TideFinder_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/TwoCanPlugIn
    
    - url: .
      branches: HEAD
      start_path: ./sources/UKTides_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/vdr_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/vfkaps_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/watchdog_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/weather_routing_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/weatherfax_pi
    
    - url: .
      branches: HEAD
      start_path: ./sources/windvane_pi

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: docs
  clean: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: |
      https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://rasbats.github.io/opencpn-plugins-manual/
