site:
  title: OpenCPN Manuals
  url: https://rasbats.github.io/ocpn-manuals/
  start_page:  manuals::index.adoc

content:
  sources:
    - url: https://github.com/Rasbats/ocpn-manuals
      branches: manual
      edit_url: true
      start_paths:
      - manuals
      - dev
      - plugins/manual
      - plugins/manual-beta
     
    - url: sources/shipdriver_pi
      branches: master
      start_path: manual/shipdriver
      edit_url: true 
      
    - url: sources/otcurrent_pi    
      branches: master
      start_path: manual/otcurrent
      edit_url: true
      
    - url: sources/photolayer_pi    
      branches: master
      start_path: manual/photolayer
      edit_url: true

    - url: sources/DR_pi    
      branches: master
      start_path: manual/dead_reckoning
      edit_url: true
      
    - url: sources/watchdog_pi
      branches: master
      start_path: manual/watchdog
      edit_url: true
      
    - url: sources/ocpn_draw_pi 
      branches: master
      start_path: manual/odraw
      edit_url: true
    
    - url: sources/radar_pi 
      branches: master
      start_path: manual/radar
      edit_url: true
    
    - url: sources/dashboard_tactics_pi
      branches: mnt151-frontend2
      start_path: manual/dash-t
      edit_url: true
    
    - url: sources/vfkaps_pi    
      branches: master
      start_path: manual/vfkaps
      edit_url: true
    
    - url: sources/sar_pi    
      branches: master
      start_path: manual/sar
      edit_url: true
    
    - url: sources/aisradar_pi   
      branches: master
      start_path: manual/ais_radar_display
      edit_url: true

    - url: sources/vdr_pi   
      branches: master
      start_path: manual/vdr
      edit_url: true

    - url: sources/gecomapi_pi   
      branches: master
      start_path: manual/googleearth
      edit_url: true

    - url: sources/iacfleet_pi   
      branches: master
      start_path: manual/iacfleet
      edit_url: true

    - url: sources/launcher_pi   
      branches: master
      start_path: manual/launcher
      edit_url: true

    - url: sources/ocpndebugger_pi   
      branches: master
      start_path: manual/debugger
      edit_url: true

    - url: sources/objsearch_pi   
      branches: master
      start_path: manual/objsearch
      edit_url: true

    - url: sources/chartscale_pi   
      branches: master
      start_path: manual/chartscale
      edit_url: true

    - url: sources/projections_pi   
      branches: master
      start_path: manual/projections
      edit_url: true

    - url: sources/celestial_navigation_pi   
      branches: master
      start_path: manual/celestial_navigation
      edit_url: true

    - url: sources/plots_pi   
      branches: master
      start_path: manual/sweep_plot
      edit_url: true

    - url: sources/weatherfax_pi   
      branches: master
      start_path: manual/weatherfax
      edit_url: true

    - url: sources/climatology_pi   
      branches: master
      start_path: manual/climatology
      edit_url: true

    - url: sources/weather_routing_pi   
      branches: master
      start_path: manual/weather_routing
      edit_url: true

    - url: sources/statusbar_pi   
      branches: master
      start_path: manual/statusbar
      edit_url: true

    - url: sources/pypilot_pi   
      branches: master
      start_path: manual/pypilot
      edit_url: true

    - url: sources/rotationctrl_pi   
      branches: master
      start_path: manual/rotationctrl
      edit_url: true

    - url: sources/calculator_pi   
      branches: master
      start_path: manual/calculator
      edit_url: true

    - url: sources/otidalplan_pi
      branches: master
      start_path: manual/otidalplan
      edit_url: true

    - url: sources/ofc_pi
      branches: master
      start_path: manual/fugawi
      edit_url: true

    - url: sources/nvc_pi
      branches: master
      start_path: manual/nv_charts
      edit_url: true

    - url: sources/s63_pi
      branches: master
      start_path: manual/s63_vector_charts
      edit_url: true

    - url: sources/oesenc_pi
      branches: master
      start_path: manual/oeSENC
      edit_url: true
    
    - url: sources/bsb4_pi
      branches: master
      start_path: manual/bsb4_charts
      edit_url: true

    - url: sources/LogbookKonni_pi   
      branches: master
      start_path: manual/logbook
      edit_url: true

    - url: sources/FindIt_pi   
      branches: master
      start_path: manual/find-it
      edit_url: true

    - url: sources/route_pi   
      branches: master
      start_path: manual/route_great_circle
      edit_url: true

    - url: sources/tactics_pi   
      branches: master
      start_path: manual/tactics
      edit_url: true

    - url: sources/polar_pi   
      branches: master
      start_path: manual/Polar
      edit_url: true

    - url: sources/NmeaConverter_pi
      branches: master
      start_path: manual/nmea_converter
      edit_url: true

    - url: sources/GPS-Odometer_pi
      branches: master
      start_path: manual/odometer
      edit_url: true

    - url: sources/windvane_pi
      branches: master
      start_path: manual/windvane
      edit_url: true

    - url: sources/rtlsdr_pi
      branches: master
      start_path: manual/rtlsdr
      edit_url: true 

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: docs
  clean: true

runtime:
fetch: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: |
      https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://rasbats.github.io/opencpn-plugins-manual/
