site:
  title: OpenCPN Developers Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://github.com/Rasbats/ocpn-dev-manual
  start_page: ocpn-dev-manual::index.adoc
  
content:
  sources:   
    - url: https://github.com/Rasbats/ocpn-dev-manual
      branches: main
      edit_url: false

ui:   
  bundle:
      url: ./ui-bundle.zip
      snapshot: true  

output:
  dir: ./docs
