site:
  title: Watchdog Manual
  url: https://localhost:8080
  start_page: watchdog::watchdog.adoc

content:
  sources:
  - url: ./
    start_path: watchdog
    branches: HEAD


ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
    

output:
  clean: true
  dir: public
